"""YAML frontmatter ↔ Pydantic serialization helpers for MarkdownEntityBackend.

Contract: design_doc/markdown_schema.md.

Pure functions (no I/O). Caller is responsible for atomic file writes,
locking, and namespace lookups. This module only deals with serializing
a `RecordedEntity` to/from the on-disk MD format.

Filename identity: ULIDs (26-char Crockford-base32). Generated by
`new_ulid()` so we don't take a new dependency on python-ulid.
"""

from __future__ import annotations

import os
import secrets
import time
from datetime import datetime, timezone
from typing import Any

import yaml  # type: ignore[import-untyped]

from altk_evolve.schema.core import Entity, RecordedEntity


# ── ULID generator (no extra deps) ─────────────────────────────────────────

# Crockford's base32 alphabet (excludes I, L, O, U for unambiguity).
_CROCKFORD_BASE32 = "0123456789ABCDEFGHJKMNPQRSTVWXYZ"  # pragma: allowlist secret


def _b32_encode(bytestr: bytes, out_len: int) -> str:
    """Crockford base32 encode `bytestr` and pad/truncate to `out_len`."""
    n = int.from_bytes(bytestr, "big")
    chars = []
    for _ in range(out_len):
        chars.append(_CROCKFORD_BASE32[n & 0b11111])
        n >>= 5
    return "".join(reversed(chars))


def new_ulid(*, ts_ms: int | None = None, rand_bytes: bytes | None = None) -> str:
    """Generate a 26-character ULID.

    Layout: 48 bits unix-time-ms (10 chars) + 80 bits random (16 chars).
    Lexicographically sortable by creation time. Test hook: pass `ts_ms`
    and/or `rand_bytes` for deterministic output.
    """
    if ts_ms is None:
        ts_ms = int(time.time() * 1000)
    if rand_bytes is None:
        rand_bytes = secrets.token_bytes(10)
    if len(rand_bytes) != 10:
        raise ValueError(f"rand_bytes must be exactly 10 bytes, got {len(rand_bytes)}")
    if ts_ms < 0 or ts_ms >= (1 << 48):
        raise ValueError("ts_ms must fit in 48 bits")
    ts_bytes = ts_ms.to_bytes(6, "big")
    return _b32_encode(ts_bytes, 10) + _b32_encode(rand_bytes, 16)


def is_valid_ulid(value: str) -> bool:
    """Lightweight syntactic check — 26 chars, all in the Crockford alphabet."""
    if len(value) != 26:
        return False
    return all(c in _CROCKFORD_BASE32 for c in value)


# ── frontmatter serialization ──────────────────────────────────────────────


_FRONTMATTER_DELIM = "---"


def _isoformat_utc(dt: datetime) -> str:
    """Emit ISO-8601 UTC with `Z` suffix (round_trip-friendly)."""
    if dt.tzinfo is None:
        raise ValueError("datetime must be timezone-aware")
    aware = dt.astimezone(timezone.utc)
    return aware.replace(tzinfo=None).isoformat(timespec="seconds") + "Z"


def _parse_isoformat(value: str) -> datetime:
    """Parse ISO-8601 with optional Z suffix into a UTC-aware datetime."""
    if value.endswith("Z"):
        value = value[:-1] + "+00:00"
    return datetime.fromisoformat(value).astimezone(timezone.utc)


def _normalize_for_yaml(value: Any) -> Any:
    """Convert datetimes, Pydantic models, and Enums into YAML-friendly primitives."""
    from enum import Enum

    if isinstance(value, datetime):
        return _isoformat_utc(value)
    if isinstance(value, Enum):
        return value.value
    if hasattr(value, "model_dump"):
        # Pydantic v2 model — recurse so nested datetimes and enums are normalized.
        dumped = value.model_dump(mode="json")
        return _normalize_for_yaml(dumped)
    if isinstance(value, dict):
        return {k: _normalize_for_yaml(v) for k, v in value.items()}
    if isinstance(value, list):
        return [_normalize_for_yaml(v) for v in value]
    return value


def serialize_entity(
    entity: RecordedEntity,
    *,
    namespace_id: str,
    authority: str = "generated",
    schema_version: str = "guideline/v1",
    extra_frontmatter: dict[str, Any] | None = None,
) -> str:
    """Serialize a RecordedEntity to MD frontmatter + body string.

    Args:
        entity: the entity to serialize. Must have a stable `id`.
        namespace_id: the namespace this entity belongs to (mirrored into frontmatter).
        authority: "generated" | "authoritative" | "canonical".
        schema_version: e.g. "guideline/v1" or "fact/v1". Use the per-track
            schema version per design_doc/markdown_schema.md.
        extra_frontmatter: backend-controlled fields (index_generation,
            slug_collision, promoted_*, etc.). Merged on top of base fields.

    Returns:
        A string `---\\n<yaml>\\n---\\n<body>` ready to write to disk.
    """
    if not is_valid_ulid(entity.id):
        # Allow non-ULID for early migrations (e.g. integer IDs from filesystem
        # backend); warn at backend level. We don't validate here so legacy
        # data can round-trip.
        pass

    base: dict[str, Any] = {
        "schema": schema_version,
        "stable_id": entity.id,
        "type": entity.type,
        "namespace": namespace_id,
        "authority": authority,
        "created_at": _isoformat_utc(entity.created_at),
        "metadata": _normalize_for_yaml(entity.metadata or {}),
    }

    # Content goes in the body if it's a string; else into frontmatter (list/dict).
    body_str: str
    if isinstance(entity.content, str):
        body_str = entity.content
    else:
        base["content"] = _normalize_for_yaml(entity.content)
        body_str = ""

    if extra_frontmatter:
        base.update(_normalize_for_yaml(extra_frontmatter))

    yaml_block = yaml.safe_dump(
        base,
        sort_keys=False,
        default_flow_style=False,
        allow_unicode=True,
    )

    parts = [_FRONTMATTER_DELIM, yaml_block.rstrip("\n"), _FRONTMATTER_DELIM]
    if body_str:
        parts.append("")
        parts.append(body_str.rstrip("\n"))
    parts.append("")  # trailing newline
    return "\n".join(parts)


def parse_md_file(text: str) -> tuple[dict[str, Any], str]:
    """Parse a frontmatter MD blob into `(frontmatter_dict, body_str)`.

    Raises ValueError if the frontmatter delimiters are missing.
    """
    lines = text.splitlines()
    if not lines or lines[0].strip() != _FRONTMATTER_DELIM:
        raise ValueError("missing opening frontmatter delimiter")
    end_idx: int | None = None
    for i, line in enumerate(lines[1:], start=1):
        if line.strip() == _FRONTMATTER_DELIM:
            end_idx = i
            break
    if end_idx is None:
        raise ValueError("missing closing frontmatter delimiter")
    yaml_text = "\n".join(lines[1:end_idx])
    body_text = "\n".join(lines[end_idx + 1 :]).strip("\n")
    frontmatter = yaml.safe_load(yaml_text) or {}
    if not isinstance(frontmatter, dict):
        raise ValueError(f"frontmatter must be a mapping, got {type(frontmatter).__name__}")
    return frontmatter, body_text


def deserialize_entity(text: str) -> tuple[RecordedEntity, dict[str, Any]]:
    """Deserialize an MD blob into `(RecordedEntity, raw_frontmatter)`.

    Returns the typed entity AND the full raw frontmatter so callers can
    access backend-controlled fields (index_generation, authority, etc.)
    without losing forward-compat data they don't recognize.
    """
    frontmatter, body = parse_md_file(text)

    required = {"stable_id", "type", "created_at"}
    missing = required - set(frontmatter)
    if missing:
        raise ValueError(f"frontmatter missing required fields: {sorted(missing)}")

    content = frontmatter.get("content")
    if content is None:
        # Body is the content for string-typed entities.
        content = body if body else ""

    entity = Entity(
        content=content,
        type=frontmatter["type"],
        metadata=frontmatter.get("metadata") or {},
    )
    recorded = RecordedEntity(
        **entity.model_dump(),
        id=frontmatter["stable_id"],
        created_at=_parse_isoformat(frontmatter["created_at"]),
    )
    return recorded, frontmatter


# ── path helpers ───────────────────────────────────────────────────────────


def entity_path_for(
    *,
    data_dir: str,
    namespace_id: str,
    entity_type: str,
    stable_id: str,
    authority: str | None = None,
    category: str | None = None,
    domain: str | None = None,
) -> str:
    """Compute the canonical on-disk path for an entity.

    Phase 1 layout (flat under namespace/type/) is acceptable; Phase 4 will
    introduce the authority/category/domain subdirs. This helper supports
    both: pass `authority`/`category` for guidelines or `domain` for facts
    if that level of structure is being used.
    """
    parts: list[str] = [data_dir, _pluralize(entity_type), namespace_id]
    if authority:
        parts.append(authority)
    if category:
        parts.append(category)
    if domain:
        parts.append(domain)
    parts.append(f"{stable_id}.md")
    return os.path.join(*parts)


def _pluralize(entity_type: str) -> str:
    """Map entity type → directory name. 'guideline' -> 'guidelines', 'fact' -> 'facts'."""
    if entity_type.endswith("s"):
        return entity_type
    return entity_type + "s"
