"""Shared entity I/O utilities for the Evolve plugin.

Handles reading and writing entities as flat markdown files with YAML
frontmatter, organized in type-nested directories.
"""

import datetime
import getpass
import os
import re
import tempfile
from pathlib import Path


# ---------------------------------------------------------------------------
# Product registry
# ---------------------------------------------------------------------------

# Default registry lives next to this file.
_PRODUCTS_CONFIG = Path(__file__).with_name("products.yaml")


def _parse_products_yaml(text):
    """Minimal YAML parser for the products.yaml format.

    Handles only the subset used by products.yaml:
      products:
        - slug: foo
          patterns:
            - pattern1
            - pattern2

    No PyYAML dependency required.
    """
    entries = []
    current = None
    in_patterns = False

    for raw in text.splitlines():
        line = raw.rstrip()
        stripped = line.lstrip()

        if stripped.startswith("- slug:"):
            if current:
                entries.append(current)
            current = {"slug": stripped[len("- slug:"):].strip(), "patterns": []}
            in_patterns = False

        elif stripped == "patterns:" and current is not None:
            in_patterns = True

        elif in_patterns and stripped.startswith("- ") and current is not None:
            current["patterns"].append(stripped[2:].strip())

        elif stripped and not stripped.startswith("#") and not stripped.startswith("-"):
            in_patterns = False

    if current:
        entries.append(current)
    return entries


def load_product_registry(entities_dir=None):
    """Return the merged product registry.

    Combines two sources in priority order:

    1. **Config file** (``.bob/lib/evolve-lite/products.yaml`` or the file
       adjacent to this module): declared products with explicit match patterns.
    2. **Existing entity folders**: any ``{type}/{product}/`` subdirectories
       under *entities_dir* that are not already in the config are added as
       folder-only products (matched by slug-token heuristic; no explicit
       patterns).

    Returns:
        list[dict]: each dict has ``"slug"`` (str) and ``"patterns"``
        (list[str], may be empty for folder-only entries).
    """
    # 1. Load from config file
    config_entries = []
    config_slugs = set()
    if _PRODUCTS_CONFIG.is_file():
        try:
            config_entries = _parse_products_yaml(
                _PRODUCTS_CONFIG.read_text(encoding="utf-8")
            )
            config_slugs = {e["slug"] for e in config_entries}
        except OSError:
            pass

    # 2. Discover folder-only products not already in config
    if entities_dir is None:
        entities_dir = get_evolve_dir() / "entities"
    entities_dir = Path(entities_dir)

    folder_slugs = set()
    if entities_dir.is_dir():
        for type_dir in entities_dir.iterdir():
            if not type_dir.is_dir() or type_dir.name.startswith("."):
                continue
            for product_dir in type_dir.iterdir():
                if (
                    product_dir.is_dir()
                    and product_dir.name != "general"
                    and product_dir.name not in config_slugs
                ):
                    folder_slugs.add(product_dir.name)

    # Merge: config entries first, then folder-only entries (no patterns)
    registry = list(config_entries)
    for slug in sorted(folder_slugs):
        registry.append({"slug": slug, "patterns": []})

    return registry


# ---------------------------------------------------------------------------
# Clone gitignore
# ---------------------------------------------------------------------------

# Files and directories that must never be committed to a publish clone.
_CLONE_GITIGNORE_CONTENT = """\
# Auto-generated by evolve-lite — do not edit manually.
# Only entity files (.evolve/entities/**) and test fixtures (.evolve/tests/**)
# belong in a publish clone.  Everything else is blocked here.

# Python environments and caches
.venv/
venv/
env/
.env
*.env
__pycache__/
*.py[cod]
*.pyo
*.pyd
.Python
pip-wheel-metadata/
*.egg-info/
dist/
build/

# Editor and IDE artifacts
.vscode/
.idea/
*.swp
*.swo
*~
.DS_Store
Thumbs.db

# Secrets and credentials
.env.*
*.pem
*.key
*.crt
*.p12
*.pfx
secrets.yaml
secrets.json

# Logs and temp files
*.log
*.tmp
*.bak
*.orig

# OS noise
.Spotlight-V100
.Trashes
ehthumbs.db
desktop.ini

# Node / JS
node_modules/
npm-debug.log*
yarn-error.log*

# Allow only entity and test content
# (everything else above is blocked; .gitignore itself is committed)
"""


def write_clone_gitignore(clone_root):
    """Write a protective .gitignore into the clone root.

    Blocks common noise files (.venv, .env, .vscode, __pycache__, etc.) from
    ever being staged or pushed from a publish clone.  Safe to call multiple
    times — overwrites only when the file does not yet exist or was written by
    a previous evolve-lite version (detected by the auto-generated header).

    Args:
        clone_root: Path to the root of the local git clone.
    """
    clone_root = Path(clone_root)
    target = clone_root / ".gitignore"

    if target.exists():
        try:
            existing = target.read_text(encoding="utf-8")
        except OSError:
            return
        # Only overwrite if this is our own auto-generated file.
        if "Auto-generated by evolve-lite" not in existing:
            return

    try:
        fd, tmp_path = tempfile.mkstemp(dir=clone_root, prefix=".gitignore.", suffix=".tmp")
        try:
            os.write(fd, _CLONE_GITIGNORE_CONTENT.encode("utf-8"))
            os.close(fd)
            fd = None
            os.replace(tmp_path, str(target))
        finally:
            if fd is not None:
                os.close(fd)
            if os.path.exists(tmp_path):
                os.unlink(tmp_path)
    except OSError:
        pass


# ---------------------------------------------------------------------------
# Logging
# ---------------------------------------------------------------------------


def _get_log_dir():
    """Get user-scoped log directory with restrictive permissions."""
    try:
        uid = os.getuid()
    except AttributeError:
        uid = getpass.getuser()
    log_dir = os.path.join(tempfile.gettempdir(), f"evolve-{uid}")
    os.makedirs(log_dir, mode=0o700, exist_ok=True)
    return log_dir


_LOG_FILE = os.path.join(_get_log_dir(), "evolve-plugin.log")


def log(component, message):
    """Append a timestamped message to the shared log file.

    Args:
        component: Short label like "retrieve" or "save".
        message: The log line.
    """
    if not os.environ.get("EVOLVE_DEBUG"):
        return
    try:
        timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        with open(_LOG_FILE, "a", encoding="utf-8") as f:
            f.write(f"[{timestamp}] [{component}] {message}\n")
    except OSError:
        pass


# ---------------------------------------------------------------------------
# Directory discovery
# ---------------------------------------------------------------------------


def get_evolve_dir():
    """Return the .evolve root directory.

    Uses ``EVOLVE_DIR`` env var if set, otherwise ``.evolve/`` in cwd.
    Does not create the directory.
    """
    env_dir = os.environ.get("EVOLVE_DIR")
    if env_dir:
        return Path(env_dir)
    return Path(".evolve")


def find_entities_dir():
    """Locate the entities directory.

    Uses :func:`get_evolve_dir` to determine the base directory, then
    returns the ``entities/`` subdirectory Path if it exists, else ``None``.
    """
    c = get_evolve_dir() / "entities"
    return c if c.is_dir() else None


def find_recall_entity_dirs():
    """Locate all directories that should be searched during recall.

    Returns the existing recall roots. Only private entities contribute to
    recall: ``entities/`` (private entities) and ``public/`` (entities
    published by the local project). Subscribed clones under
    ``entities/subscribed/`` are excluded.
    """
    evolve_dir = get_evolve_dir()
    entities_dir = evolve_dir / "entities"
    public_dir = evolve_dir / "public"
    candidates = [entities_dir, public_dir]
    return [path for path in candidates if path.is_dir()]


def get_default_entities_dir():
    """Return (and create) the default entities directory.

    Uses ``EVOLVE_DIR`` if set, falls back to ``.evolve/entities/``.
    """
    base = get_evolve_dir() / "entities"
    base.mkdir(parents=True, exist_ok=True)
    return base.resolve()


# ---------------------------------------------------------------------------
# Banality check (shared by save_entities.py and refine.py)
# ---------------------------------------------------------------------------

# Universally-known single-step practices that add no recall value
_BANAL_PATTERNS = [
    # Generic Python env / packaging
    r"^activate\s+(the\s+)?virtual\s+(environment|env)\s*\.?\s*$",
    r"^install\s+dependencies\s*\.?\s*$",
    r"^run\s+(the\s+)?(application|app|script|program)\s*\.?\s*$",
    r"^set\s+up\s+(a\s+)?virtual\s+(environment|env)\s*\.?\s*$",
    r"^create\s+a\s+requirements\.txt\s*\.?\s*$",
    r"^import\s+(a\s+)?module\s*\.?\s*$",
    # Basic file ops
    r"^(create|write|make)\s+a\s+(file|directory|folder)\s*\.?\s*$",
    r"^read\s+(a\s+)?file\s*\.?\s*$",
    r"^write\s+to\s+(a\s+)?file\s*\.?\s*$",
    r"^delete\s+(a\s+)?file\s*\.?\s*$",
    # Basic git
    r"^git\s+(add|commit|push|pull|status|log)\s*\.?\s*$",
    r"^create\s+a\s+(git\s+)?branch\s*\.?\s*$",
    # Fatally vague
    r"^when\s+performing\s+",
    r"^do\s+something\s*\.?\s*$",
    r"^use\s+(the\s+)?\w+\s*\.?\s*$",
]

_BANAL_RE = [re.compile(p, re.IGNORECASE) for p in _BANAL_PATTERNS]


def check_banality(entity):
    """Return ``(is_banal, reason)`` for *entity*.

    An entity is banal when it would provide no recall value because:

    1. **Empty / trivially short** — content ≤ 30 chars with no backtick command.
    2. **Common-sense pattern** — content or trigger matches a curated list of
       universally-known single-step practices.
    3. **Pure trigger restatement** — content body is a near-verbatim copy of the
       trigger, adding nothing (Jaccard ≥ 0.85 between the two).
    4. **Slug tautology** — content or trigger consists only of tokens already
       present in the filename slug, meaning the entity says nothing that isn't
       already encoded in its own name.

    Returns:
        tuple[bool, str]: ``(True, reason_string)`` if banal, else ``(False, "")``.
    """
    content = entity.get("content", "").strip()
    trigger = entity.get("trigger", "").strip()

    # 1. Too short and no command
    if len(content) <= 30 and not re.search(r"`[^`]+`", content):
        return True, f"content too short ({len(content)} chars) and contains no command"

    combined = f"{content} {trigger}".lower()

    # 2. Common-sense pattern match
    for pat in _BANAL_RE:
        if pat.search(content.lower()) or pat.search(trigger.lower()):
            return True, f"matches common-sense pattern: '{pat.pattern}'"

    # 3. Trigger restatement — content is essentially the trigger re-worded
    def _tok(t):
        words = re.findall(r"[a-z0-9]+", t.lower())
        _stop = {"the", "a", "an", "and", "or", "in", "on", "at", "to", "for",
                 "of", "with", "by", "from", "as", "is", "was", "are", "be",
                 "when", "after", "while", "if", "how", "this", "that"}
        return {w for w in words if w not in _stop and len(w) > 2}

    c_tok = _tok(content)
    t_tok = _tok(trigger)
    if c_tok and t_tok:
        inter = len(c_tok & t_tok)
        union = len(c_tok | t_tok)
        jac = inter / union
        if jac >= 0.85:
            return True, f"content is a near-verbatim restatement of trigger (Jaccard={jac:.2f})"

    return False, ""


# ---------------------------------------------------------------------------
# Slugify / filename helpers
# ---------------------------------------------------------------------------


def slugify(text, max_length=60, product=None):
    """Convert *text* to a filesystem-safe slug with optional product prefix.

    >>> slugify("Use temp files for JSON transfer!")
    'use-temp-files-for-json-transfer'
    >>> slugify("Activate environment", product="watson-orchestrate")
    'watson-orchestrate-activate-environment'
    """
    text = text.lower()
    text = re.sub(r"[^a-z0-9]+", "-", text)
    text = text.strip("-")
    
    # Add product prefix if provided
    if product:
        product_slug = re.sub(r"[^a-z0-9]+", "-", product.lower()).strip("-")
        text = f"{product_slug}-{text}"
    
    # Truncate at max_length, but don't break in the middle of a word
    if len(text) > max_length:
        text = text[:max_length].rsplit("-", 1)[0]
    return text or "entity"


def unique_filename(directory, slug):
    """Return a Path that doesn't collide with existing files in *directory*.

    Tries ``slug.md``, then ``slug-2.md``, ``slug-3.md``, etc.
    """
    directory = Path(directory)
    candidate = directory / f"{slug}.md"
    if not candidate.exists():
        return candidate
    n = 2
    while True:
        candidate = directory / f"{slug}-{n}.md"
        if not candidate.exists():
            return candidate
        n += 1


# ---------------------------------------------------------------------------
# Markdown <-> dict conversion
# ---------------------------------------------------------------------------

_FRONTMATTER_KEYS = ("type", "name", "trigger", "trajectory", "owner", "source", "visibility", "published_at", "version", "atomic_skills", "product", "derived_from_failure")


# Optional markdown body sections, in serialisation order.
# Maps entity dict key -> markdown heading display name.
# Single-word keys: heading == key.capitalize().
# Multi-word keys: heading is the value (with spaces / title-case).
_BODY_SECTIONS = ("rationale", "success_rubric", "requirements", "imports", "dependencies", "documentation", "changelog")

# Heading display names for keys that don't map via simple .capitalize()
_SECTION_HEADING_OVERRIDE = {
    "success_rubric": "Success Rubric",
}

def _section_heading(key):
    """Return the markdown heading text for a body-section key."""
    return _SECTION_HEADING_OVERRIDE.get(key, key.capitalize())

def _heading_to_key(heading):
    """Reverse-map a matched heading back to the entity dict key."""
    _reverse = {v.lower(): k for k, v in _SECTION_HEADING_OVERRIDE.items()}
    return _reverse.get(heading.lower(), heading.lower())


def entity_to_markdown(entity):
    """Serialize an entity dict to markdown with YAML frontmatter.

    Args:
        entity: dict with keys ``content``, and optionally ``type``,
                ``trigger``, ``rationale``, ``requirements``, ``imports``,
                ``dependencies``, ``documentation``.

    Returns:
        A string suitable for writing to a ``.md`` file.
    """
    lines = ["---"]
    for key in _FRONTMATTER_KEYS:
        val = entity.get(key)
        if val:
            lines.append(f"{key}: {val}")
    lines.append("---")
    lines.append("")

    content = entity.get("content", "")
    lines.append(content)

    for section_key in _BODY_SECTIONS:
        val = entity.get(section_key)
        if val and val.strip():
            heading = f"## {_section_heading(section_key)}"
            lines.append("")
            lines.append(heading)
            lines.append("")
            lines.append(val.strip())

    lines.append("")
    return "\n".join(lines)


def markdown_to_entity(path):
    """Parse a markdown entity file back into a dict.

    Handles YAML frontmatter with simple ``key: value`` lines (no nested
    structures, no PyYAML dependency).

    Recognised body sections (parsed into entity dict keys):
        ## Rationale, ## Requirements, ## Imports, ## Dependencies,
        ## Documentation

    Returns:
        dict with ``content`` plus any recognised section keys.
    """
    path = Path(path)
    text = path.read_text(encoding="utf-8")

    entity = {}

    # Split frontmatter
    if text.startswith("---"):
        parts = text.split("---", 2)
        if len(parts) >= 3:
            frontmatter = parts[1].strip()
            body = parts[2]
            for line in frontmatter.splitlines():
                line = line.strip()
                if not line:
                    continue
                key, _, value = line.partition(":")
                key = key.strip()
                value = value.strip()
                if key and value:
                    entity[key] = value
        else:
            body = text
    else:
        body = text

    # Split body into content + known optional sections.
    # A section begins at "## <Heading>" and runs until the next "## " heading
    # or end of string.  Content is everything before the first known heading.
    body = body.strip()

    # Build a regex that matches any of the known section headings
    _known_headings = "|".join(re.escape(_section_heading(s)) for s in _BODY_SECTIONS)
    _section_re = re.compile(
        rf"^## ({_known_headings})\s*$", re.MULTILINE | re.IGNORECASE
    )

    first_match = _section_re.search(body)
    if first_match:
        content = body[: first_match.start()].strip()
    else:
        content = body

    if content:
        entity["content"] = content

    # Walk through all section matches and capture text until the next heading
    matches = list(_section_re.finditer(body))
    for i, m in enumerate(matches):
        section_name = _heading_to_key(m.group(1))
        section_start = m.end()
        section_end = matches[i + 1].start() if i + 1 < len(matches) else len(body)
        section_text = body[section_start:section_end].strip()
        if section_text:
            entity[section_name] = section_text

    return entity


def _parse_frontmatter_lines(lines):
    """Parse simple YAML-style frontmatter lines into a dict."""
    entity = {}
    for raw_line in lines:
        line = raw_line.strip()
        if not line:
            continue
        key, _, value = line.partition(":")
        key = key.strip()
        value = value.strip()
        if key and value:
            entity[key] = value
    return entity


def _parse_frontmatter_only(path):
    """Parse only the frontmatter section from a markdown entity file."""
    path = Path(path)
    try:
        with path.open(encoding="utf-8") as handle:
            if handle.readline().strip() != "---":
                return {}

            frontmatter_lines = []
            found_closing = False
            for line in handle:
                if line.strip() == "---":
                    found_closing = True
                    break
                frontmatter_lines.append(line)
    except (OSError, UnicodeDecodeError):
        return {}

    if not found_closing:
        return {}

    return _parse_frontmatter_lines(frontmatter_lines)


def _manifest_path(path):
    """Return a manifest path relative to the project root (parent of the evolve dir).

    This keeps manifest paths stable regardless of the caller's working directory,
    so hooks invoked from a subdirectory still emit ``.evolve/entities/...`` paths.
    """
    path = Path(path)
    try:
        project_root = get_evolve_dir().resolve().parent
        return str(path.resolve().relative_to(project_root))
    except ValueError:
        return str(path)


def dedupe_manifest_entries(entries):
    """Return deterministically ordered manifest entries with exact dedupe."""
    normalized = []
    seen = set()
    for entry in sorted(entries, key=lambda item: (item["path"], item["type"], item["trigger"])):
        key = (entry["path"], entry["type"], entry["trigger"])
        if key in seen:
            continue
        seen.add(key)
        normalized.append(entry)
    return normalized


def load_manifest(root_dir):
    """Load a frontmatter-only manifest from a recall root."""
    root_dir = Path(root_dir)
    entries = []
    for md in sorted(root_dir.glob("**/*.md")):
        if md.is_symlink() or ".git" in md.parts:
            continue
        # Skip the subscribed/ subtree — those are read-only remote clones and
        # may contain stale entity versions that conflict with local entities.
        if "subscribed" in Path(md).resolve().parts:
            continue

        entity = _parse_frontmatter_only(md)
        entity_type = entity.get("type")
        trigger = entity.get("trigger")
        if not entity_type or not trigger:
            continue

        entry = {
            "path": _manifest_path(md),
            "type": entity_type,
            "trigger": trigger,
        }
        if entity.get("derived_from_failure") == "true":
            entry["derived_from_failure"] = True
        entries.append(entry)

    return dedupe_manifest_entries(entries)


# ---------------------------------------------------------------------------
# Bulk load / write
# ---------------------------------------------------------------------------


def load_all_entities(entities_dir):
    """Glob ``**/*.md`` under *entities_dir* and parse each file.

    Returns:
        list of entity dicts.
    """
    entities_dir = Path(entities_dir)
    entities = []
    for md in sorted(entities_dir.glob("**/*.md")):
        try:
            entity = markdown_to_entity(md)
            if entity.get("content"):
                entities.append(entity)
        except OSError:
            pass
    return entities


def write_entity_file(directory, entity):
    """Write a single entity as a markdown file under *directory*.

    The file is placed in a ``{type}/{product}/`` subdirectory.  Uses atomic
    write (write to ``.tmp``, then ``os.rename``).

    Returns:
        Path to the written file.
    """
    _ALLOWED_TYPES = {"guideline", "atomic-skill", "skill-flow"}
    entity_type = entity.get("type", "guideline")
    if not isinstance(entity_type, str) or entity_type not in _ALLOWED_TYPES:
        entity_type = "guideline"
    entity["type"] = entity_type
    
    # Get product for organization
    product = entity.get("product", "general")
    
    # Create type/product directory structure
    type_dir = Path(directory) / entity_type / product
    type_dir.mkdir(parents=True, exist_ok=True)

    # Prefer the explicit name field for the slug; fall back to content
    slug_source = entity.get("name") or entity.get("content", "entity")
    slug = slugify(slug_source, product=product)
    content = entity_to_markdown(entity)

    # Write to a unique temp file first (avoids predictable .tmp collisions)
    fd, tmp_path = tempfile.mkstemp(dir=type_dir, suffix=".tmp", prefix=slug)
    target = None
    try:
        os.write(fd, content.encode("utf-8"))
        os.close(fd)
        fd = None

        # Atomically claim the target using O_EXCL; retry on race
        while True:
            target = unique_filename(type_dir, slug)
            try:
                claim_fd = os.open(str(target), os.O_CREAT | os.O_EXCL | os.O_WRONLY)
                os.close(claim_fd)
                break
            except FileExistsError:
                continue

        os.replace(tmp_path, target)
        return target
    except BaseException:
        if fd is not None:
            os.close(fd)
        if os.path.exists(tmp_path):
            os.unlink(tmp_path)
        # Clean up the 0-byte placeholder if the replace didn't happen
        if target and os.path.exists(str(target)) and os.path.getsize(str(target)) == 0:
            os.unlink(str(target))
        raise
